### PR TITLE
MCS-984 Replace Instantiate

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
I believe I've found a solution to the "holes" issue, making good use of @alexcraneunity's new Floor prefab. I've replaced the problematic `Instantiate` call with a call to `AddressablesUtil.Instance.InstantiateAddressablesGameObject` which seems to have worked. The integration tests run for me, as well as manual testing of scenes containing floor sections. (Note that I've also removed "holes" as the default scene file in the MCS Starter Scene.) Please double-check my changes to ensure this solution works for you and your test cases as well.

This branches off Alex's PR https://github.com/NextCenturyCorporation/ai2thor/pull/180

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
@jaudick For testing:
- Since this PR includes a change affecting addressable assets, you'll need to build addressables locally in order to test it outside of the Unity Editor. See the instructions here: https://nextcentury.atlassian.net/wiki/spaces/MCS/pages/2280161285/Adding+Content+To+Addressables#Locally-testing-addressables:
- I used MCS python version 0.5.0 (`git checkout 0.5.0`)
- I ran the integration tests, as well as scenes like [holes.json](https://github.com/NextCenturyCorporation/ai2thor/blob/development/unity/Assets/Addressables/MCS/Scenes/holes.json) and [floor_textures.json](https://github.com/NextCenturyCorporation/ai2thor/blob/development/unity/Assets/Addressables/MCS/Scenes/floor_textures.json) using scripts like [run_just_rotate.py](https://github.com/NextCenturyCorporation/MCS/blob/development/machine_common_sense/scripts/run_just_rotate.py)

**Comment by alexcraneunity** [comment]
Just finished testing this, and it works with no errors beyond the usual invalid shader error. The only thing I have noticed is that the floor seems to be missing the material it had previously and just has a plain white/beige material. Is this expected? 
image

**Comment by ThomasSchellenbergNextCentury** [comment]
@alexcraneunity You're right -- good catch! I had missed that last night, but I coincidentally ran into it a few minutes ago. Since we're no longer cloning the current floor, and instead instantiating new floor sections from the original prefab, some properties that were previously cloned, like the floor material for the current scene, were not being correctly applied to the new floor sections. I've just pushed a fix for this issue, so please try it out and let me know if it works for you as well!

**Comment by alexcraneunity** [comment]
Just checked and it works with the correct material. Approved.

**Review by alexcraneunity — APPROVED** [review]

**Review by kdrumm — APPROVED** [review]
Once I tested with MCS 0.5.0, everything worked.  Code looks good and individual tests were showing materials on floor.

**Pull request merged**
