### PR TITLE
MCS - 1835 - Novel blobs

### PR DESCRIPTION
**Pull request by NDCACI**

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
@NDCACI Good progress! A few more gotchas:
1. The BoxCollider on each BoundingBox must be set as inactive (uncheck the little checkbox in the Inspector view).
2. The previous box colliders seem to have disappeared. Due to the way the AI2-THOR scripts work, each prefab is supposed to have an inactive BoundingBox BoxCollider (with the SimObjInvisible Layer), and an active collider (with the SimObjVisible Layer and the SimObjPhysics Tag).
3. The BoundingBox and all visibility point GameObjects should be set on the corresponding properties in the Sim Obj Physics Script in each blob prefab.
4. The BoundingBox for `blob_14` is not wide enough.
5. The BoundingBox for `blob_14_nose` is not tall enough.
6. The `blob_20` prefab still seems slightly offset, like it needs to be moved a little in the +Z direction.
7. The noses on `17` and `22` are backward.

Note that I'm not terribly concerned about noses sticking out of the bounding boxes, since most of the previous blobs are that way already.

**Comment by ThomasSchellenbergNextCentury** [comment]
Posted my feedback on the other PR: https://github.com/NextCenturyCorporation/mcs-private/pull/529#issuecomment-1832470348

Almost there!

**Review by phile-caci — APPROVED** [review]
Spot checked objects in Unity, looks good.  Some blobs in blobs.json has a y = .5 so they start off in the air, shouldn't effect anything though.

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci Yeah, I just had them all start floating in the air because I was too lazy to assign specific Y positions for each blob :)

**Pull request merged**
