### PR TITLE
MCS-1719 - Refactor Novel Tools

### PR DESCRIPTION
**Pull request by phile-caci**
1. The v1/v2/v3 version of the tools have been removed from the addressables.
2. MCSMain.InitializeGameObject looks for the v1/v2/v3 tools in objectConfig.type. If it finds the v1/v2/v3 version it changes to the not v1/v2/v3 versionm (i.e tool_rect_0_75_x_5_00_v1 becomes tool_rect_0_75_x_5_00), then it sets the materialFile and materials to M_YFMM_15, M_YFMM_35 or M_YFMM_36
3. You'll need to rebuild Addressables and AI2Thor.
4. You can test with `python generate_secret_scenes.py -p tooluse -t ToolUse --sort-hypercube`
5. In scene id 23 (tooluse_0001_23.json), the tool will have a v1/v2/v3.
6. Running the scene through MCS with the AI2Thor executable pointed to the new one built from this branch
7. The v1 will be a brown tool, v2 will be pink and v3 will be green.

Let me know if I missed anything!

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci Are we planning an update on the scene generator (mcs-private) side as well? While it's **fantastic** that this is backwards compatible, ideally we'd stop using `v1`/`v2`/`v3` and start using `materials` in the ILE and hypercubes (assuming it's not too much work). (And my apologies if you've already mentioned something about this and I've simply forgotten.)

**Comment by phile-caci** [comment]
@ThomasSchellenbergNextCentury ,
Yes, want me to handle the scene generator under a separate ticket or with this one?
 
> @phile-caci Are we planning an update on the scene generator (mcs-private) side as well? While it's **fantastic** that this is backwards compatible, ideally we'd stop using `v1`/`v2`/`v3` and start using `materials` in the ILE and hypercubes (assuming it's not too much work). (And my apologies if you've already mentioned something about this and I've simply forgotten.)

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci Hmm, I don't think I care how you track it in JIRA. As long as it's still on your radar (and preferably sometime soon).

**Comment by phile-caci** [comment]
Cool, I'll do it today as a part of this ticket.

> @phile-caci Hmm, I don't think I care how you track it in JIRA. As long as it's still on your radar (and preferably sometime soon).

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Review by rartiss55 — APPROVED** [review]

**Pull request merged**
