### PR TITLE
MCS-1024

### PR DESCRIPTION
**Pull request by alexcraneunity**
Jira: https://nextcentury.atlassian.net/browse/MCS-1024

Note: I will likely squash all associated commits and amend the commit message before merging.

### CODE REVIEW

**Comment by alexcraneunity** [comment]
This isn't necessarily ready for merging, but I'm more creating this to get feedback on the implementation, as well as bring up some issues with the current approach. 

Initially, I wanted to loop through every object and get the color from its material. However, some objects have only one material, while some objects are made up of many sub-objects that each have their own material, with no particular ordering to them. For an object like the desk with the green top, it is clear that the desired color to be returned would be green, though it also has parts with brown materials. There didn't seem to be a reliable way to know which sub-object to get the color from.

Instead, I implemented a camera-based approach. This uses a secondary camera that travels above every object and looks down at them, grabbing a color from the point at the center of their transform by creating a RenderTexture from the camera's viewpoint and reading the center pixel from it. You can see this working with the chest object in the picture below, and it works with many other scenes. The UI square on the left is the color-camera's feed, and the UI square on the right is the color it finds.
image

However, this creates some issues when objects either move, are spawned in later in the scene, or their center point may not be where we want to grab the color from. See the examples below.

The color camera doesn't seem to move to the right spot for the object:
image

This object is dropped in later, so it only sees the ground at first and gets its color:
image

Does anyone have any comments or suggestions for this approach?
There are some errors I get in the integration tests, but I will save those for a later comment.

**Comment by JuanRMarquez-Ortiz** [comment]
My first thought was to take all the textures from all the materials of the object, look for the dominant color, and use that. I would imagine this would be slow at runtime, but it could be done at build time. Then we can add that color as a reference to one of the monobehaviors on the object.

**Comment by alexcraneunity** [comment]
> My first thought was to take all the textures from all the materials of the object, look for the dominant color, and use that. I would imagine this would be slow at runtime, but it could be done at build time. Then we can add that color as a reference to one of the monobehaviors on the object.

@JuanRMarquez-Ortiz  I thought about this approach as well, though as you said it has its own caveats. For example, there are different ways to determine the dominant color. First we have to get a color from each material - would this get just a single pixel from the material, or would it be the average of all RGBs (pixels) within that material? Then, we have to determine the dominant color of all sub-objects. I could see a case where we have two different "brown" wood materials, but each return slightly different brown RGBs based on our method, so we would need a way to associate both of them as brown. 

The build time idea is a good suggestion, but I'm also wondering if that would be feasible since these objects aren't spawned into the scene until the scene is loaded at runtime.

**Comment by JuanRMarquez-Ortiz** [comment]
By doing it at build time, what I mean is to create an editor script that
takes an object, instantiates it in the scene, does the snapshot to get the
color, sets the color on the object, then destroys it. Do this for all
objects on the asset bundles. It'll take a while, but by the end all the
colors will be assigned.

As for how to generate the color, I'd probably start with the average of
all the pixels in a texture, then take the total number of pixels in that
texture as a "score". Do the same for all other textures in the object,
then use the color with the highest score. This will give you the
predominant color without muddying it with others that may be diametric
opposites and would fudge the result too much towards a color that isn't
even represented in the object.

Once you have the color you can maybe mess with the saturation to better
match the average saturation in the object as well, or the saturation of
the most saturated pixel in the object. Not sure what would serve the
purpose best. I'd go for the first idea, see the result, and then fudge
around with it until it looks best.

For example, averaging the color in a single texture may make a mess. In
that case you may want to score different hues on a spectrum, then get the
hue with the highest score.

**Comment by alexcraneunity** [comment]
After discussion, we have decided not to pursue this task due to the required work being much more involved than originally anticipated.

**Pull request closed without merging**
