### PR TITLE
MCS-1950 Multi platform file locking (Windows Build)

### PR DESCRIPTION
**Pull request by phile-caci**
Some updates for AI2Thor to build on windows.

Replaced fcntl with portalocker.  

Seems to work... it's building on windows at least.  Doesn't look like it's affected the linux build.  Someone should test on MacOS too. Will have to circle back to MCS to make sure that all runs on windows (another ticket).

### CODE REVIEW

**Review by NDCACI — APPROVED** [review]

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci We're going to have to:
1. Update Jenkins to automatically build the Windows executable and put it on S3
2. Update `unity_executable_provider.py` in the Python API to correctly auto-download on Windows

Is that correct?

**Review by ThomasSchellenbergNextCentury — CHANGES_REQUESTED** [review]
I'm testing on Windows 10 by editing the files in my `venv/lib/site-packages/ai2thor/` folder, and I've run into a bunch of issues:

1. I'm finding more modules that apparently aren't available on Windows, including `termios` and `tty`. Simply commenting out the related code seems to break things. I can continue to dig into it if we think it's worthwhile.
2. The `os.mkfifo` command is also unavailable on Windows, though I'm seeing some suggestions online to use `os.pipe` instead.
3. The major thing is: we don't actually use the code in this repo; we use the publicly released `ai2thor` python module on pypi. It would be a big task to start building and releasing our own `ai2thor` module (though our experience with github workflows on the MCS repo would help), and we'd need to overhaul the `machine_common_sense` code to use the new module. This is why we've [monkey patched](https://github.com/NextCenturyCorporation/MCS/blob/development/machine_common_sense/controller.py#L49) the `ai2thor` code in the past.

Not saying it can't be done, but there's a lot to think about, now that I understand the situation better. Maybe the time investment is still worth it; maybe it isn't.

**Review by rartiss55 — APPROVED** [review]
Ran build on a Mac + copy pasted the *.py files into my virtual environment and installed portalocker. Was able to start things up and run integration tests at oracle level.

**Comment by phile-caci** [comment]
superseded by: https://github.com/NextCenturyCorporation/MCS/pull/701

**Pull request closed without merging**
