### PR TITLE
MCS-1829 Fix Missing Script Warnings

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Suggestions for reviewing this PR:
1. Checkout this branch
2. Verify you're using the Localhost addressables profile
3. Build addressables locally
4. Build Unity locally
5. Start an HTTP server in ServerData
6. Run the integration tests using the following branch: https://github.com/NextCenturyCorporation/MCS/pull/667
7. Review your Player.log file for any "The referenced script on this Behavior ... is missing!" warnings
8. Try running a scene containing a bowl, cup, plate, or TV (`bowl_3` or whatever) and make sure you don't see any "missing" warnings
9. If you're so inclined, you can review my individual commits... Just don't bother with the ones that start with "Replaced..." (they're the ones with the most changed files, and it's just me moving those files around)

Changes:
- When MCS first started, I had copied the "Assets/Physics/", "Assets/Prefabs", and "Assets/QuickMaterials/" folders into the Resources folder (which is now the Addressables folder). However, I should have MOVED them, instead of copying them, because I discovered later that some of the copied files contained child objects which still referenced assets in the original folders. Since these original assets may have been causing problems, I went ahead and moved them the right way, replacing the duplicate files in the Addressables folder, and updating the Addressable Asset Groups.
- Removed the AI2-THOR addressable asset group. This group contained all AI2-THOR assets we aren't specifically using on MCS, in case the assets we **are** using had secondary dependencies. I'm very confident at this point that these assets aren't currently needed.
- Removed some unnecessary AI2-THOR debug and experimental assets (that we aren't using).
- Removed missing scripts from FPSController, SceneManager, PhysicsSceneManager, and various Decal prefabs.
- Updated addressable asset groups to include recently-added container prefabs.
- Made copies of apples, bowls, cups, and plates, and removed missing scripts from them. Updated file paths in the object registries for these entries.

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
LGTM,

- Cleared all my caches
- Rebuilt addressables with localhost
- built unity
- started http server in ServerData
- Ran integration from MCS using my local unity (--mcs_unity_build_file_path ~/mcs/mymcsai2thor/MCS-AI2-THOR-Unity-App-v0.6.5.x86_64)
- Player.log didn't have "The referenced script on this Behavior ... is missing!" warnings
- Also ran a scene with "bowl_3" (from mcs-private: webenabled/scenes/bravo_0001_01.json), didn't see any "missing" warnings in the player.log

I did see these Null References in the log (didn't seem to affect anything):
```
NullReferenceException: Object reference not set to an instance of an object
  at SimObjPhysics.Start () [0x000e4] in /home/ple/mcs/ai2thor/unity/Assets/Scripts/SimObjPhysics.cs:434 
 
(Filename: /home/ple/mcs/ai2thor/unity/Assets/Scripts/SimObjPhysics.cs Line: 434)

NullReferenceException: Object reference not set to an instance of an object
  at SimObjPhysics.LateUpdate () [0x00001] in /home/ple/mcs/ai2thor/unity/Assets/Scripts/SimObjPhysics.cs:474 
 
(Filename: /home/ple/mcs/ai2thor/unity/Assets/Scripts/SimObjPhysics.cs Line: 474)
```

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci I've seen Null Reference Exceptions pop up before (for a while now), but keep forgetting to build Unity in development mode and take time to track them down. I'll add another ticket for this. Thank you for pointing that out!

**Review by rartiss55 — APPROVED** [review]
Deleted ServerData/ and rebuilt addressables, ran integration tests. Left a note on the Python API PR, but a couple tests failed and then reran with no issue. Didn't see any behavior missing errors in Player.log. Also put a bowl_3 in the playroom scene and didn't see any issue in the logs. 

Wanted to note that this showed up for me in the Unity Editor when I switched to this branch:
```
A meta data file (.meta) exists but its asset 'Assets/Addressables/MCS/AI2-THOR/Objects/Physics/Scene Setup Prefabs' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.

GUID [a8930c7b5724e48429a46e0293649dbe] for asset 'Assets/Addressables/MCS/AI2-THOR/Objects/Physics/SimObjsPhysics' conflicts with:
  'Assets/Physics/SimObjsPhysics' (current owner)
Assigning a new guid.
```
I've worked around similar stuff before (at least with regards to the latter error) so if no one else is seeing that, no big deal + things seem to work fine. For me, this is the files that get modified as a result:
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    unity/Assets/Addressables/MCS/AI2-THOR/Objects/Physics/Scene Setup Prefabs.meta
	modified:   unity/Assets/Addressables/MCS/AI2-THOR/Objects/Physics/SimObjsPhysics.meta


Untracked files:
  (use "git add <file>..." to include in what will be committed)
	unity/Assets/MagicMirror.meta
	unity/Assets/Physics/SimObjsPhysics.meta
	unity/Assets/Prefabs.meta
	unity/Assets/QuickMaterials.meta

**Comment by ThomasSchellenbergNextCentury** [comment]
@rartiss55 I double-checked after merging, and I don't see any meta files that weren't already in the repo, so I think it was just an artifact from switching branches.

**Pull request merged**
