### PR TITLE
MCS-1569 remove unnecessary ai2thor stuff

### PR DESCRIPTION
**Pull request by jaudick**

### CODE REVIEW

**Review by ThomasSchellenbergNextCentury — COMMENTED** [review]
Integration tests pass. Lots to review. Head still hurts. Oof.

None of the removals jumped out to me as being potentially problematic.

Not necessarily an issue, but there appears to be a weird mix of commenting-out unused methods/calls and deleting them entirely (unless the diffs are playing tricks on me). Given how much code we're removing, deleting unused code entirely (rather than just commenting it out) might actually make future merges with AI2-THOR easier, especially given how dumb diff tools can be (most of the diffs look horrendous). Thoughts? Concerns?

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury I deleted all commented out code. Reviewing should be much easier now.

**Review by phile-caci — APPROVED** [review]
Looks good on my end. All integration test pass (except for the structural object ones that should be fixed once development is merged)

Can we completely remove `unity/Assets/Scripts/coffeemachine.cs`? (in the future)

Didn't seem to be an issue, but I'll mention it just in case. In the player log I was getting this message:

`ActionFinished called with agentState not in processing` (hadn't seen this one before)
```
ActionFinished called with agentState not in processing 
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController:actionFinished(Boolean, AgentState, Object) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs:314)
UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController:actionFinished(Boolean, Object) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs:329)
UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController:sopApplyForce(ServerAction, SimObjPhysics, Single) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs:722)
UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController:sopApplyForce(ServerAction, SimObjPhysics) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs:736)
UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController:ApplyForceObject(ServerAction) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs:703)
UnityStandardAssets.Characters.FirstPerson.PhysicsRemoteFPSAgentController:PushObject(ServerAction) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/PhysicsRemoteFPSAgentController.cs:2298)
MCSController:PushObject(ServerAction) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSController.cs:594)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController:ProcessControlCommand(ServerAction) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs:1037)
MCSController:ProcessControlCommand(ServerAction) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSController.cs:550)
AgentManager:ProcessControlCommand(String) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/AgentManager.cs:714)
<EmitFrame>d__65:MoveNext() (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/AgentManager.cs:648)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
 
(Filename: /home/ple/mcs/ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs Line: 314)
```

I was also get some NullReference messages:
```
Last Action Status = SUCCESSFUL
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController:actionFinished(Boolean, AgentState, Object) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs:322)
UnityStandardAssets.Characters.FirstPerson.BaseFPSAgentController:actionFinished(Boolean, Object) (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs:329)
MCSController:SimulatePhysicsOnce() (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSController.cs:738)
<SimulatePhysicsSaveImagesIncreaseStep>d__79:MoveNext() (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSController.cs:801)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutineManaged2(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/MonoBehaviour.bindings.cs:91)
MCSController:SimulatePhysics() (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSController.cs:709)
MCSMain:Update() (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSMain.cs:263)
 
(Filename: /home/ple/mcs/ai2thor/unity/Assets/Scripts/BaseFPSAgentController.cs Line: 322)

NullReferenceException: Object reference not set to an instance of an object
  at MCSController.CheckIfTargetIsVisibleAtStart () [0x0000d] in /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSController.cs:1317 
  at MCSMain+<CheckIfTargetIsVisible>d__101.MoveNext () [0x00086] in /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSMain.cs:393 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00020] in /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17 
 
(Filename: /home/ple/mcs/ai2thor/unity/Assets/Scripts/MCSController.cs Line: 1317)

MCS: AGENT MANAGER EMIT FRAME
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
<EmitFrame>d__65:MoveNext() (at /home/ple/mcs/ai2thor/unity/Assets/Scripts/AgentManager.cs:537)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
 
(Filename: /home/ple/mcs/ai2thor/unity/Assets/Scripts/AgentManager.cs Line: 537)
```

**Comment by jaudick** [comment]
@phile-caci 
1) The next pr removes coffee machine and many many more scripts.
2) `ActionFinished called with agentState not in processing` this message is ok it only affects the editor.
3) This happens whenever a goal is not present in the scene. As a separate ticket we could add a check for it but its not an issue as is.

**Review by rartiss55 — APPROVED** [review]
LGTM / saw some integration test issues same as Phi but sounds like that's just branches being slightly out of date.

**Comment by phile-caci** [comment]
> @phile-caci
> 
> 1. The next pr removes coffee machine and many many more scripts.
> 2. `ActionFinished called with agentState not in processing` this message is ok it only affects the editor.
> 3. This happens whenever a goal is not present in the scene. As a separate ticket we could add a check for it but its not an issue as is.

Thanks @jaudick !

**Pull request merged**
