### PR TITLE
Simulation Agent Movement

### PR DESCRIPTION
**Pull request by jaudick**
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/552)
There are a lot of comments in this code because I needed them to keep track of the different conditions. I also serialized a lot of private variables so I could see them in the inspector as I found those very useful. I can remove both of these but I think they are helpful.

### CODE REVIEW

**Review by kdrumm — COMMENTED** [review]
This all looks good to me except I'm getting Integration Test 115 failures now.  I'm really not sure why or what could have caused it.

**Comment by jaudick** [comment]
@kdrumm I cant seem to replicate it what are the errors?

**Comment by kdrumm** [comment]
> @kdrumm I cant seem to replicate it what are the errors?

Starting on step 9, I have soccer ball position (and distance).  I wonder if I have a different set of UnityAssetStore assets or something along those lines.  We can wait for someone else to test and if it all works for them, I'm willing to approve (and then figure out what is going on on my side)

**Comment by jaudick** [comment]
@kdrumm Test 115 is fixed now

**Review by kdrumm — APPROVED** [review]

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Lots of good code comments -- thanks! This looks great for now, though I'm going to hammer on the behavior more in your next PR :)

**Pull request merged**
