### PR TITLE
MCS-1676 Fixed interactive support relations, which was completely broken

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Tentative fix for Jed's recently-discovered critical bug: https://machinecommonsense.slack.com/archives/CTR31V12M/p1676777978495809

Needs to be included in 0.6.5 (code freeze)

Running integration tests overnight. Planning to add new integration tests for Support Relations and Shell Game use cases.

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
Looks good to me!
(Tested 5 scenes)
Before:
image


After:
image

**Review by brianpippin — APPROVED** [review]
Code looks fine, Integration tests pass.  Worried that we need an integration test for this stat but perhaps that can wait till after the release.

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin Just made a PR with the new integration tests: https://github.com/NextCenturyCorporation/MCS/pull/649

**Comment by brianpippin** [comment]
> @brianpippin Just made a PR with the new integration tests: [NextCenturyCorporation/MCS#649](https://github.com/NextCenturyCorporation/MCS/pull/649)

Running them now with this build, will let you know.

**Review by jaudick — APPROVED** [review]

**Pull request merged**
