### PR TITLE
Mcs 1647 add novel tool materials v123

### PR DESCRIPTION
**Pull request by phile-caci**
Added 3 sets of the tool_rect, each set has a mat on the tool:
v1 has:
- Assets/Addressables/MCS/UnityAssetStore/YughuesFreeMetalMaterials/Materials/M_YFMM_15.mat (brown texture)
image

v2 has:
- Assets/Addressables/MCS/UnityAssetStore/YughuesFreeMetalMaterials/Materials/M_YFMM_34.mat (pink texture)
image

v3 has:
- Assets/Addressables/MCS/UnityAssetStore/YughuesFreeMetalMaterials/Materials/M_YFMM_36.mat (green texture)
image

The corresponding ticket for the scene generator:
https://github.com/NextCenturyCorporation/mcs-private/pull/388

### CODE REVIEW

**Comment by jaudick** [comment]
I think this can be done without additional objects.

Screen Shot 2023-03-15 at 3 49 15 PM

Since the tool materials are already in the TOOL_MATERIAL_REGISTRY inside of MCSConfig you should be able to just set the materials property on the object.

### **Here is me setting it**

Screen Shot 2023-03-15 at 3 47 16 PM

### **And here is the result**

Screen Shot 2023-03-15 at 3 47 05 PM

Notice the tool type though in the second screenshot. In my version it is not a v1,v2,v3. It is the normal type. So there shouldn't be a need for all of the new objects. Setting the materials on the base tool type should be enough.

**Review by jaudick — CHANGES_REQUESTED** [review]
I think this can be done without additional objects.

Screen Shot 2023-03-15 at 3 49 15 PM

Since the tool materials are already in the TOOL_MATERIAL_REGISTRY inside of MCSConfig you should be able to just set the materials property on the object.

### **Here is me setting it**

Screen Shot 2023-03-15 at 3 47 16 PM

### **And here is the result**

Screen Shot 2023-03-15 at 3 47 05 PM

Notice the tool type though in the second screenshot. In my version it is not a v1,v2,v3. It is the normal type. So there shouldn't be a need for all of the new objects. Setting the materials on the base tool type should be enough.

**Comment by ThomasSchellenbergNextCentury** [comment]
@jaudick You totally missed the conversation we had about this while you were on vacation :)

Phi originally implemented it the way you suggested: https://github.com/NextCenturyCorporation/ai2thor/pull/306

But we realized this would require a new Unity release, which we don't want to do. So we're (unfortunately) doing it this way for Eval 6, but will go back to doing it the "right way" for the 0.7.0 release.

**Comment by ThomasSchellenbergNextCentury** [comment]
@jaudick No worries. Your notes are totally valid -- you missed the whole discussion! I wish we could have saved Phi the trouble of making those extra prefabs, but alas...

**Comment by phile-caci** [comment]
> Looks good. Novel tools rendered properly when running via Python.
> 
> Do we want to keep the old PR open, but wait to merge it in until we're preparing the 0.7.0 release? We'll need to make a few minor code changes there too for backwards compatibility.
> 
> #306

Not a problem, I'll reopen it.

**Pull request merged**
