### PR TITLE
MCS-1150 Bug Fix: Moving into Lightweight Objects Automatically Shoves Them Aside

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
In the past, the TA1 agent was able to Move into lightweight objects (mass <= 2) and shove them aside automatically. This behavior was broken in a recent commit. This PR fixes that behavior.

### CODE REVIEW

**Review by kdrumm — COMMENTED** [review]
Everything looks good to me, however testing integration tests with the dev MCS build crashed on test 73.  Should I be testing against a different version of MCS?

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm Hmm... I happened to be testing on Jacob's branch MCS-1123, and integration test 73 passes there, but I now see that it fails on development, and I don't know why... Nothing on that branch should affect this test... I'll do some digging.

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury it also passes on MCS-1123 but not development for me. The failure on development fails on my new configurable reward score code. It looks like my check for if the penalties are None is working as intended. I'm checking by printing out their values after the is None check. But it still seems to think its None after and I'm not sure why

**Comment by ThomasSchellenbergNextCentury** [comment]
@jaudick Now that you've merged MCS-1123 into development, I've merged the latest from development into this branch, rebuilt Unity, and tried rerunning the integration tests using the latest from development on the python side, and am getting the same error. Is there a chance that something didn't get merged properly with regard to the lava reward?

**Comment by ThomasSchellenbergNextCentury** [comment]
The work @kdrumm is doing on his PR has fixed most tests: https://github.com/NextCenturyCorporation/MCS/pull/490

However, I think this branch broke the seesaw... Investigating now.

**Comment by ThomasSchellenbergNextCentury** [comment]
I fixed seesaws and a few integration tests. This PR is again ready for review. Corresponding python PR: https://github.com/NextCenturyCorporation/MCS/pull/492

**Review by kdrumm — APPROVED** [review]

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury there appears to be a merge conflict now but this looks great

**Review by jaudick — APPROVED** [review]

**Pull request merged**
