### PR TITLE
MCS - 2028 - I and T tools added

### PR DESCRIPTION
**Pull request by NDCACI**

### CODE REVIEW

**Review by phile-caci — COMMENTED** [review]
Looks good, do we need to adjust the box collider the Receptacle?

image


image

**Comment by NDCACI** [comment]
> Receptacle

I'm not sure, the isosceles tools are a bit weird

Screenshot 2024-01-30 at 9 02 43 AM

**Comment by phile-caci** [comment]
regarding receptacle: yeah, I think the receptacle only matters if we're gonna place objects on it.  which we never did...

**Review by phile-caci — APPROVED** [review]
Everything looks good to me... test both tools with push/pull and rotate (obstructed)

**Pull request merged**
