### PR TITLE
MCS-1193 Added simulation-controlled agents to the MCS world.

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Accomplishments:
- Added an `agentSettings` scene file option to configure agent body and clothing colors and accessories, and updated MCSMain to use these settings.
- Wrote an MCSSimulatedAgent Unity script to map the agentSettings onto the agent prefabs.
- Created 8 agent prefabs (4 male, 4 female) that are modified versions of the original "PrefabMaker" prefabs (from the ToonPeople asset package), but with the MCSSimulatedAgent script added.
- Added the agent prefabs to the object registry file, with appropriate bounding boxes and visibility points (they already had colliders).
- Created a new scene for testing.
- Added all the new addressables to the addressable asset group.

How to use the `agentSettings`:
- Each agent setting maps to an array index. For example, `"chest": 0` will set the "chest" body part (including shirt and arms) to the "chest" element at index 0. Different body parts may have different numbers of options, but everything has at least 2.
- The settings that end in "Material" configure the material (color/texture) on the corresponding body part. For example, `"chestMaterial": 1` will set the material of the "chest" body part to the material element at index 1 for that chest. Different body parts may have different numbers of options, but everything has at least 4.
- Some parts are toggleable, specifically: hair (default on), glasses (default off), jacket/sweater (default off), tie (default off), beard (default off, men only).
- ~A setting of `-1` or any other invalid number will randomize the body part or material each time the scene is loaded. We wouldn't use this for the eval data -- it's just a fallback. Nevertheless, I'm not sure if this is the best approach. Potential alternatives may include: throwing an initialization error and crashing the scene; using a default index.~
- I'm planning to add full documentation on how many elements are in each array.

To finalize this ticket:
- Ensure we as a team approve of this implementation approach (through this PR).
- ~Create a corresponding python PR with the new scene file properties.~
- ~Update documentation with `agentSettings` information.~
- ~Add some integration tests.~

Separate tickets:
- ~Changing the agents' default animations (if desired).~
- Generating scenes with agents in the ILE.

How you can test:
- Copy over the agent assets from mcs-private into your local Unity addressables folder (specifically `UnityAssetStore/ToonPeople/*` and `UnityAssetStore/Custom/agent_*`)
- In the Unity Editor, run the `agents_interactive` scene to view the agent models. It contains 6 sets of 4 agents each: 4 sets of consistently-colored male/female agents, and 2 sets of independently, randomly-colored male/female agents. PLEASE NOTE: you will see that the agents each have an "idle" animation that does not pause along with the physics simulation.
- Review how agents are configured via the `agentSettings` in the `agents_interactive.json` scene file.
- Look at how the agent prefabs (`UnityAssetStore/Custom/agent_*.prefab`) are constructed in the Unity Editor.

### CODE REVIEW

**Comment by kdrumm** [comment]
For me, some of the jackets and shorts were clipping in and out of what was below them giving a weird effect.  I'm not sure we can do anything about it, but we want to consider how this will affect performers.

**Comment by ThomasSchellenbergNextCentury** [comment]
> For me, some of the jackets and shorts were clipping in and out of what was below them giving a weird effect. I'm not sure we can do anything about it, but we want to consider how this will affect performers.

Do you have any screenshots you could share? It's definitely worth investigating.

**Comment by kdrumm** [comment]
I'd be curious if you do or do not see the same thing.  Potentially I did something wrong.

They are more obvious in the editor as they shift, but you can see it here:

Screenshot from 2022-03-10 08-33-42
Screenshot from 2022-03-10 08-33-21
Screenshot from 2022-03-10 08-33-00

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm Hmm... I'm not seeing any clipping... I'll keep digging though... Hopefully I didn't forget to commit any files.

Screenshot from 2022-03-10 13-55-36

Screenshot from 2022-03-10 13-54-43

Screenshot from 2022-03-10 13-54-58

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm Alright now I'm seeing the clipping issue too. So weird. It seems to be isolated to just the suit jackets, though, so, worst case, we can disable them. If we move forward with the toon people, I'll see if the clipping persists when run via python.

**Comment by ThomasSchellenbergNextCentury** [comment]
Changes from this morning:
- I updated the agent prefabs in the mcs-private repo: `UnityAssetStore/Custom/agent_*`
- I added an `isElder` setting to toggle elder skin.
- I changed the behavior of using an invalid index in the agent settings to instead use a default of 0 (previously, it would assign a random valid index). Allowing a scene to have random elements didn't seem appropriate in hindsight.
- Created a corresponding python PR: https://github.com/NextCenturyCorporation/MCS/pull/541

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury @kdrumm I only see the clipping in the play window, the scene window appears good. Very odd
Screenshot from 2022-03-15 09-59-58

**Comment by ThomasSchellenbergNextCentury** [comment]
Today's changes:
- I've updated the agent prefabs again, to deactivate the "playanimation" script and assign them types (see MCSSimulationAgent). Grab the latest from the mcs-private repo: `UnityAssetStore/Custom/agent_*`
- I've updated the code to only assign the default animation ("idle1") if no other animation has been assigned to that agent via the "actions" property in the JSON file.
- I removed male agent 1 and female agent 3 from the example scene and the object registry file, to retain them as novel objects in a future eval.

**Review by jaudick — APPROVED** [review]

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury I think this looks good to merge!

**Pull request merged**
