### PR TITLE
MCS-658 Center of Mass Scene File Property for Gravity Support Hypercubes

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
- Added `letter_l_wide_tall` object
- Added the centerOfMass scene configuration file property to set an object's center of mass.
- Added the resetCenterOfMass scene configuration file property to reset an object's center of mass when it bounces off of the ground (when its Y velocity becomes positive).

### CODE REVIEW

**Review by kdrumm — APPROVED** [review]
LGTM

**Comment by kdrumm** [comment]
I mistakenly approved.  The code looks good to me, but im working on testing with the scene gen ...

**Comment by kdrumm** [comment]
This fails for me with marshmallow.  I think we need to resolve that along with all these changes.

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm 

> This fails for me with marshmallow. I think we need to resolve that along with all these changes.

Ah, you're right. I was testing it on MCS master (without the schema changes) rather than development. I guess I should fix that now then...

**Comment by kdrumm** [comment]
Approved

**Review by brianpippin — APPROVED** [review]

**Pull request merged**
