### PR TITLE
MCS-1136: Add a Turntable (Lazy Susan) Object in Unity

### PR DESCRIPTION
**Pull request by alexcraneunity**
This is a new pull request following up on the previous PR (#255), with a new clean branch based off of development. This PR also introduces a new ReceptacleRotationUtil class, which is added to a persisted object in the MCS-Starter-Scene, and is used in both MCSMain and SimObjPhysics. 
[MCS ir tests](https://github.com/NextCenturyCorporation/ai2thor/pull/263)

### CODE REVIEW

**Comment by jaudick** [comment]
I created a more complex json for you with stacking objects on top of the cog. The code changes look good and this layer of stacking rotations all worked as intended. Can you make a few integration tests on the MCS branch, one of them including this scene below testing stacking rotations.
`{
    "name": "rotating_cog_example_with_stacking",
    "version": 1,
    "ceilingMaterial": "AI2-THOR/Materials/Walls/WallDrywallWhite",
    "floorMaterial": "AI2-THOR/Materials/Fabrics/RUG4",
    "wallMaterial": "AI2-THOR/Materials/Walls/YellowDrywall",
    "roomDimensions": {
        "x": 5,
        "y": 5,
        "z": 8
    },
    "performerStart": {
        "position": {
            "x": 0,
            "z": 0
    },
        "rotation": {
            "x": 0,
            "y": 0
        }
    },
    "objects":
        [{
            "id": "block_blank_a",
            "type": "block_blank_wood_cube",
            "salientMaterials": ["wood"],
            "materials": ["UnityAssetStore/Wooden_Toys_Bundle/ToyBlocks/meshes/Materials/blue_1x1"],
            "shows": [{
                "stepBegin": 0,
                "position": {
                    "x": 0,
                    "y": 0.055,
                    "z": 2.25
                },
                "rotation": {
                    "x": 0,
                    "y": 1,
                    "z": 0
                },
                "scale": {
                    "x": 2,
                    "y": 1,
                    "z": 2
                }
            }]
        }, {
            "id": "block_blank_c",
            "type": "block_blank_wood_cube",
            "salientMaterials": ["wood"],
            "materials": ["UnityAssetStore/Wooden_Toys_Bundle/ToyBlocks/meshes/Materials/green_1x1"],
            "shows": [{
                "stepBegin": 0,
                "position": {
                    "x": 0,
                    "y": 0.155,
                    "z": 2.25
                },
                "rotation": {
                    "x": 0.01,
                    "y": 1,
                    "z": 0
                },
                "scale": {
                    "x": 1,
                    "y": 1,
                    "z": 1
                }
            }],
            "rotates": [{
                "stepBegin": 1,
                "stepEnd": 9,
                "vector": {
                    "x": 0,
                    "y": 33,
                    "z": 0
                }
            }]
        }, {
            "id": "block_blank_d",
            "type": "block_blank_wood_cylinder",
            "salientMaterials": ["wood"],
            "materials": ["UnityAssetStore/Wooden_Toys_Bundle/ToyBlocks/meshes/Materials/red_1x1"],
            "shows": [{
                "stepBegin": 0,
                "position": {
                    "x": 0,
                    "y": 0.26,
                    "z": 2.25
                },
                "rotation": {
                    "x": 0,
                    "y": 1,
                    "z": 0
                },
                "scale": {
                    "x": 1,
                    "y": 1,
                    "z": 1
                }
            }]
        }, {
            "id": "block_blank_f",
            "type": "block_blank_wood_cube",
            "salientMaterials": ["wood"],
            "materials": ["UnityAssetStore/Wooden_Toys_Bundle/ToyBlocks/meshes/Materials/yellow_1x1"],
            "shows": [{
                "stepBegin": 0,
                "position": {
                    "x": 0,
                    "y": 0.434,
                    "z": 2.25
                },
                "rotation": {
                    "x": 0,
                    "y": 1,
                    "z": 0
                },
                "scale": {
                    "x": 1,
                    "y": 2,
                    "z": 1
                }
            }]
        }, {
        "id": "rotating_cog_a",
        "type": "rotating_cog",
        "shows": [{
            "stepBegin": 0,
            "position": {
                "x": 0.2,
                "y": 0.01,
                "z": 2.00
            }
        }],
        "rotates": [{
            "stepBegin": 1,
            "stepEnd": 9,
            "vector": {
                "x": 0,
                "y": 10,
                "z": 0
            }
        }],
        "structure": true
    }, {
        "id": "apple_a",
        "type": "apple_1",
        "shows": [{
            "stepBegin": 0,
            "position": {
                "x": 0.3,
                "y": 0.02,
                "z": 2.00
            },
            "scale": {
                "x": 1,
                "y": 1,
                "z": 1
            }
        }]
    }
    ]
}`

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Looks great! I remember trying a couple other scenarios before (scaling the cog, and positioning a Toon Person on top of it) and it working correctly. All of the integration tests pass. However, I do agree with Jacob's suggestion of adding an integration test or two. (And good example with the stack of blocks as well!)

**Review by jaudick — APPROVED** [review]

**Comment by brianpippin** [comment]
@jaudick or @ThomasSchellenbergNextCentury if one of you could shepherd this ticket with Alex having departed that would be great.

**Comment by ThomasSchellenbergNextCentury** [comment]
Yeah I think we're just waiting on the last few integration tests.

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Re-approving

**Pull request merged**
