### PR TITLE
Trying to fix an issue in which 'picking up' the floor/walls returns an OBSTRUCTED status

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Changes:
- Moved around an existing chuck of code in PhysicsRemoteFPSAgentController.PickupObject so that it returns an action status of NOT_PICKUPABLE if given the floor or walls.
- Updated the code to set the lastActionStatus before calling actionFinished so I can log the lastActionStatus within actionFinished.

Concerns:
- Does my change to PickupObject have any unintended side-effects?
- Does something similar happen with other actions?

Slack Thread: https://machinecommonsense.slack.com/archives/CTR31V12M/p1605676601224000?thread_ts=1605620665.215700&cid=CTR31V12M

### CODE REVIEW

**Comment by rartiss55** [comment]
Thanks for fixing this! And logging the lastActionStatus is a good idea. 

> Concerns:
> 
> * Does my change to PickupObject have any unintended side-effects?

So this only happens in the Unity editor for me (works completely fine when the app is built and running from the Python API), but I’m not able to pick up anything? I get the NOT_INTERACTABLE error. Is this user error or something I’m forgetting to do? Also wondering if this check is even needed (I would think this would be covered by NOT_PICKUPABLE). 

> * Does something similar happen with other actions?
> 
I can make a separate ticket if you like, but I went through and tested out the actions. Its good you brought this up, because we do need to better account for the fact that performers might not have correctly selected the thing they actually want to interact with (for the examples listed below, I’m talking about accidentally selecting the floor or another structural object):
- Push/PullObject – “OBSTRUCTED” would be thrown first before “OUT_OF_REACH” or “NOT_PICKUPABLE”
- Open/CloseObject – “OUT_OF_REACH” would be thrown first before “NOT_OPENABLE”
- PutObject – “OUT_OF_REACH” would be thrown first before “NOT_RECEPTACLE”
I think for the “OUT_OF_REACH” ones, this was an unintended consequence from separating the structural objects from the objects list (because it can’t find the object in the “visible objects” list). We can change the ordering of the errors like you did for PickupObject, or have a specific code for trying to interact with structural objects (use “not interactable”, or something new like “structural object”?) I went back and forth on this but changing the ordering is probably fine, and either way we should add some more info to the docs on what “NOT_PICKUPABLE”, etc might mean.

**Comment by ThomasSchellenbergNextCentury** [comment]
@rartiss55 

> So this only happens in the Unity editor for me (works completely fine when the app is built and running from the Python API), but I’m not able to pick up anything? I get the NOT_INTERACTABLE error.

Can you please verify that the object ID input fields are blank?

**Comment by ThomasSchellenbergNextCentury** [comment]
@rartiss55 OK, I updated the code for PullObject/PushObject. The code for CloseObject, OpenObject, and PutObject would need a complete redesign, though, because it returns OUT_OF_REACH if it can't find the object (with a null check), so moving the code around wouldn't work in these cases. However, since those changes aren't currently a concern for TA1, I think what's here is fine for now.

**Comment by rartiss55** [comment]
> @rartiss55
> 
> > So this only happens in the Unity editor for me (works completely fine when the app is built and running from the Python API), but I’m not able to pick up anything? I get the NOT_INTERACTABLE error.
> 
> Can you please verify that the object ID input fields are blank?

That was it -- thanks!

**Comment by rartiss55** [comment]
> @rartiss55 OK, I updated the code for PullObject/PushObject. The code for CloseObject, OpenObject, and PutObject would need a complete redesign, though, because it returns OUT_OF_REACH if it can't find the object (with a null check), so moving the code around wouldn't work in these cases. However, since those changes aren't currently a concern for TA1, I think what's here is fine for now.

@ThomasSchellenbergNextCentury Sounds good. I made a ticket for later for those other actions in case its needed: https://nextcentury.atlassian.net/browse/MCS-499

**Review by rartiss55 — APPROVED** [review]

**Pull request merged**
