### PR TITLE
Removed ai2thor physics script from grid floor

### PR DESCRIPTION
**Pull request by jaudick**
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/585)
Note that this means floor sections will no longer be visible as they lack visibility points. The script and visibility points were removed from the prefab in the MCS/Custom addresables folder

### CODE REVIEW

**Comment by rartiss55** [comment]
Did some testing -- is not having floor visibility + not sending back any metadata pertaining to floor sections at oracle level going to be an issue for TA1 during training?

**Comment by rartiss55** [comment]
Did some testing -- is not having floor visibility + not sending back any metadata pertaining to floor sections at oracle level going to be an issue for TA1 during training?

**Comment by ThomasSchellenbergNextCentury** [comment]
If you're not doing it already, this PR will require updates to the integration tests. All of the failures seem reasonable to me: either the `structural_objects_count` is off by 1, because the floor isn't returned in the metadata anymore, or the returned action status for interacting with the floor is different (specifically in tests 41 and 42). However, the fact that none of the other test cases failed (especially in the tests with objects rolling along the floor) makes me a bit more optimistic about this change.

I'm still not 100% comfortable (maybe like 95%) with making a change like this so late in our dev cycle, given how often the legacy (unfamiliar) AI2-THOR code refers to this script, but I also don't want a "gut feeling" on my part to hold back a potentially very useful performance improvement...

I still agree with my previous comment that we should have the TA1s sign-off on this change before making it final.

**Comment by jaudick** [comment]
> However, the fact that none of the other test cases failed (especially in the tests with objects rolling along the floor)
@ThomasSchellenbergNextCentury I believe the reason is that all of the floors still have updated rigid bodies which is what affects those interactions, not the physics script. I can update the integration tests. 

I think the performance boost is significant enough that its worth the change this late in our dev cycle but it needs to be discussed.

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Approving this. When Eval 5 is done, we can merge this into development and bang on it for a while. We have plenty of time until Eval 6 to identify and fix any potential issues with this change.

**Review by rartiss55 — APPROVED** [review]

**Comment by jaudick** [comment]
@rartiss55 @brianpippin @ThomasSchellenbergNextCentury This needs approval after the latest commit

**Review by rartiss55 — APPROVED** [review]

**Pull request merged**
