### PR TITLE
RotateObject - Troubleshooting rotation with receptacles and their contained objects

### PR DESCRIPTION
**Pull request by rartiss55**
(MCS-88)

Trying to rotate bowl with an apple in it (try 90 or 180 degrees) results in apple flying upwards.
image

Currently debugging in Unity: added playroom-mcs-88 scene file for this, which has receptacles containing objects (mainly using bowl_a/apple_a). Use ‘H’ to RotateObject, and fill out how many degrees/along which axis using the rotate object direction vector in Debug Discrete Agent Controller. 

** **Am now wondering if we even want to rotate receptacles with items in them, considering we want to expand what a receptacle means (for instance, I was initially thinking of rotating receptacles along the lines of bowls/boxes, but do we really want to rotate a block with something on top of it? I would think that was more of an obstruction).**

Things tried (+ various combinations of what’s indicated below):
-	Move apple slightly above receptacle, doesn’t fly away (forces/torque likely a factor). 

- Deactivating object colliders (probably should've realized this would result in things falling through the floor). 

-	Revisited AddRelativeTorque
My understanding was this wouldn’t be what we wanted because it wouldn’t rotate something x degrees but tries to rotate something in a direction, and how much it rotates is affected by rigidbody attributes.

-	Messing with various rigidbody attributes
o	Mass/drag – decreases distance at which apple flies away from bowl, but I don't think I could find the correct settings to apply to every situation. 
o	Changing collision detection settings
o	Making objects kinematic – results in either the same behavior or items stuck in floor (see screenshot below).
image
o	Using position constraints -- fixes the apple in the same spot and just rotates the bowl, which gets mixed results depending on how far you plan on rotating things (works for extreme cases, but a smaller rotation results in the apple seeming like it fell through the bottom of the bowl since it is fixed). 

-	FixedJoint – This seems like it changed the physics of all objects together, so that both the bowl and apple fly away and land in some corner of the room, instead of just the apple. 
-	Deactivating object inside receptacle – stopped going down this path because I realized it creates the same issue as the one we’re trying to resolve here, since the object would then be invisible (like with held objects). 
-	Additionally, rotating boxes with things in them seems to result in the box rotating and the object inside of it not moving, similar to position constraints (see below screenshot)
image

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
Hey @rartiss55 

This is a great writeup.  Thanks for being so thorough.

The issue with the boxes may have to do with the fact that the `position` in the `Transform` on the `mesh` child component inside each box is non-zero (offset).  However, fixing that won't help to solve the overall problem.

I'm now thinking that the best answer here may not actually be instantaneously changing the object's hard-coded rotation itself (since the sudden clipping is what's causing the objects to collide and fly around in an unrealistic manner once the physics simulation is unpaused).  Instead, maybe we should have RotateObject behave like PushObject/PullObject, where we apply a force that rotates the object as part of the physics simulation.  In this case, we'd use ApplyTorque, and we'd need to play with the numbers to determine what a realistic amount of torque would be (remember that it's proportional to the mass of the object).  This way, if you flip over the bowl, it happens as part of the physics simulation (over the course of multiple frames), and the apple should move appropriately as part of the physics simulation as well.  This should also prevent objects from clipping into the floor or walls.

This method should also work with the block stacking example.  I think it's OK to rotate a block at the bottom of a stack, as long as the blocks stacked above it topple over in a realistic way.

What do you think?

**Comment by rartiss55** [comment]
Thanks @ThomasSchellenbergNextCentury! That makes sense, and yes that would address some of the other concerns with adjacent objects and what would realistically happen if things were to suddenly rotate. I had trouble moving things with ApplyTorque previously, but its probably like you said, finding the appropriate/realistic inputs proportional to the mass.

**Comment by rartiss55** [comment]
And although there's a path forward, I'll keep this draft open just in case there's any more troubleshooting needed.

**Comment by rartiss55** [comment]
Will likely do RotateInHand instead for eval 3 -- closing.

**Pull request closed without merging**
