### PR TITLE
Addressables Support

### PR DESCRIPTION
**Pull request by erick-u**
MCS Private Assets for Addressables:
https://github.com/NextCenturyCorporation/mcs-private/tree/MCS-547-Addressables

Follow the same steps for setting up the project except to the new Addressables folder instead of Resources.
`UnityAssetStore -> Addressables/MCS/UnityAssetStore`

Steps for setting up build as normal

1. Place UnityAssetStore assets into Addressables/MCS folder
Note: If you are switching to this branch, make sure to delete Resources/UnityAssetStore from the project
2. Launch project and let it compile
3. Switch to the desired platform (Linux/OSX)
4. Build the project

Links to ready builds:
Linux: https://drive.google.com/drive/folders/1HT0yC40uvL8S3abRgzfuPl8Mdv4Zxq_J?usp=sharing
OSX: https://drive.google.com/drive/folders/1cwvOvUrJbybORcVRdrIo2ynAC_B7q3al?usp=sharing

Documentation:
https://nextcentury.atlassian.net/wiki/spaces/MCS/pages/2109899025/Addressables%2BAsset%2BBundles

Pre-Caching Addressables assets
```
import subprocess

args = ["./MCS-AI2-THOR-Unity-App-4.0.x86_64", "CACHEADDRESSABLES"]
subprocess.call(args)
```

Related PR:
MCS Private: https://github.com/NextCenturyCorporation/mcs-private/pull/31
MCS: https://github.com/NextCenturyCorporation/MCS/pull/358

### CODE REVIEW

**Review by kdrumm — COMMENTED** [review]
Bonus points for making the build much faster!
I'm having issues using this with development integration tests.  I suspect I did something wrong, but im not sure.  I removed the UnityAssetStore from Resources and added them from your addressables branch into the addressables folder.

**Comment by erick-u** [comment]
It could be that building an initial addressable package configures the builds correctly to point to the bundles on AWS. You won't need to upload the built addressable bundles but simply building them once should "configure" your next actual build to be configured correctly. This will be a good test to confirm this, and see if there is a workaround to not require this.

**Comment by kdrumm** [comment]
Integration test ran successfully!

**Review by kdrumm — APPROVED** [review]
works for me now.  Ran all integration tests and some manual tests.  

I was also able to build my own addressables group.  We should make sure that process is documented somewhere (if it isn't already)

**Comment by ThomasSchellenbergNextCentury** [comment]
@erick-u I see you updated the location for the UnityAssetStore folder in the README, which is great. Are there any other specific file or line diffs you think we should review? GitHub (understandably) crashes on me when I try to switch over to the diff tab since so many files have changed.

**Comment by ThomasSchellenbergNextCentury** [comment]
@erick-u 

> Documentation:
https://nextcentury.atlassian.net/wiki/spaces/MCS/pages/2109899025/Addressables%2BAsset%2BBundles

Would you mind adding this link to either the ai2thor repo's README, or the mcs-private repo's README (or maybe both repos)? That will make it easier to find when we need to add new assets to the system in the future.

**Comment by ThomasSchellenbergNextCentury** [comment]
> Steps for setting up build as normal
> Place UnityAssetStore assets into Addressables/MCS folder

FYI for other reviewers: You'll need to delete the `Resources/MCS/UnityAssetStore` folder too, or else you'll get compile errors.

**Comment by ThomasSchellenbergNextCentury** [comment]
@erick-u 

> Pre-Caching Addressables assets

We should add this as a script to the MCS repo (probably make the file path to the Unity app configurable via command line argument) and add a step to the Download section of the MCS repo's README.

**Review by JuanRMarquez-Ortiz — APPROVED** [review]

**Comment by erick-u** [comment]
> @erick-u I see you updated the location for the UnityAssetStore folder in the README, which is great. Are there any other specific file or line diffs you think we should review? GitHub (understandably) crashes on me when I try to switch over to the diff tab since so many files have changed.

Yeah, I tried to filter out / narrow down to the specific things but the page is unusable. Here are the primary code changes and additions that were made.

The only changes to any core classes are MCSMain: 
https://github.com/NextCenturyCorporation/ai2thor/blob/a492cea27fcfa6e768513f5dee5d78d091381876/unity/Assets/Scripts/MCSMain.cs#L104
https://github.com/NextCenturyCorporation/ai2thor/blob/a492cea27fcfa6e768513f5dee5d78d091381876/unity/Assets/Scripts/MCSMain.cs#L221-L226
https://github.com/NextCenturyCorporation/ai2thor/blob/a492cea27fcfa6e768513f5dee5d78d091381876/unity/Assets/Scripts/MCSMain.cs#L682
https://github.com/NextCenturyCorporation/ai2thor/blob/a492cea27fcfa6e768513f5dee5d78d091381876/unity/Assets/Scripts/MCSMain.cs#L1163
https://github.com/NextCenturyCorporation/ai2thor/blob/a492cea27fcfa6e768513f5dee5d78d091381876/unity/Assets/Scripts/MCSMain.cs#L1180
https://github.com/NextCenturyCorporation/ai2thor/blob/a492cea27fcfa6e768513f5dee5d78d091381876/unity/Assets/Scripts/MCSMain.cs#L1201
https://github.com/NextCenturyCorporation/ai2thor/blob/a492cea27fcfa6e768513f5dee5d78d091381876/unity/Assets/Scripts/MCSMain.cs#L1264

The newly added scripts are:
Utility script which wraps memory management for easy transition from Resources.Load to addressables.
https://github.com/NextCenturyCorporation/ai2thor/blob/MCS-547-Addressables/unity/Assets/Scripts/Addressables/AddressablesUtil.cs

Editor scripts for tools and build post-processor 
https://github.com/NextCenturyCorporation/ai2thor/blob/MCS-547-Addressables/unity/Assets/Scripts/Addressables/Editor/AddressablesEditor.cs

Util functions being used by addressable scripts
https://github.com/NextCenturyCorporation/ai2thor/blob/MCS-547-Addressables/unity/Assets/Scripts/MCSUtil.cs

**Comment by erick-u** [comment]
> > Steps for setting up build as normal
> > Place UnityAssetStore assets into Addressables/MCS folder
> 
> FYI for other reviewers: You'll need to delete the `Resources/MCS/UnityAssetStore` folder too, or else you'll get compile errors.

Since we do not track these files in this repo "Switch" to this branch does not properly delete these files. It may be worth noting this somewhere in the documentation.

**Comment by erick-u** [comment]
> @erick-u
> 
> > Pre-Caching Addressables assets
> 
> We should add this as a script to the MCS repo (probably make the file path to the Unity app configurable via command line argument) and add a step to the Download section of the MCS repo's README.

That is what I am currently working on. Passing in the build path as an argument as well as printing a message when caching has been completed. I plan to add this to `MCS/scripts` repo.

**Comment by erick-u** [comment]
> @erick-u
> 
> > Documentation:
> > https://nextcentury.atlassian.net/wiki/spaces/MCS/pages/2109899025/Addressables%2BAsset%2BBundles
> 
> Would you mind adding this link to either the ai2thor repo's README, or the mcs-private repo's README (or maybe both repos)? That will make it easier to find when we need to add new assets to the system in the future.

Will do.

**Comment by ThomasSchellenbergNextCentury** [comment]
> Here are the primary code changes and additions that were made...

@erick-u This was super helpful -- Thank you! It's nice to have all of the addressables code in one place so we can easily see how it's done!

1. Interesting way of doing class and method block comments. Is this a C#/Unity standard? Just curious -- I'm learning!
```c#
/// <summary>
/// Runtime helper for interfacing with addressables content. Manages memory for assets loaded/unloaded from runtime.
/// </summary>
```

2. AddressablesUtil, starting at line 168: Is this code necessary?
```c#
                        // this does not seem to be returning different results
                        //if (dls.Result > 0)
                        {
                            locations.Add(location);
                            addedLocations.Add(hash);
                        }
```

3. AddressablesEditor, starting at line 100: Does the naming of the `aa` folders have any special significance here, or was that just chosen arbitrarily? Also, should these folder paths be global variables?

```c#
#if UNITY_STANDALONE_LINUX
        string sourceDir = Path.Combine(Path.GetDirectoryName(Application.dataPath), "CachedAddressableLink/Linux/aa");
        string dataDir = Path.ChangeExtension(pathToBuiltProject, null) + "_Data/";
        string targetDir = Path.Combine(dataDir, "StreamingAssets/aa");
#endif

#if UNITY_STANDALONE_OSX
        string sourceDir = Path.Combine(Path.GetDirectoryName(Application.dataPath), "CachedAddressableLink/OSX/aa");
        string targetDir = Path.Combine(pathToBuiltProject, "Contents/Resources/Data/StreamingAssets/aa");
#endif   
```

4. MCSUtil, line 33: We should either make a ticket for this task and add a TODO with the ticket number to this comment, or remove the commented-out code if it won't be needed in the future.

```c#
        // For some reason this is not working on linux, should reinvestigate later as this is the correct way to do this.
        //Application.Quit();
```

**Comment by erick-u** [comment]
@ThomasSchellenbergNextCentury 
1. Ah, it's very common for both Visual Studio to show comments when hovering over methods and it was very helpful in other projects for automated documentation generation. 

2. No, the commented line can be removed at this point.

3. `aa` is the actual name generated through addressable and is required. This is a workaround to allow builds to work without needing to build bundles initially to get the catalog information. I will be documenting this shortly. 
Folder paths should absolutely be global/static, good catch. 

4. I actually confirmed this ended up being a user error. I have pushed the fix for this.

**Review by rartiss55 — APPROVED** [review]

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Comment by ThomasSchellenbergNextCentury** [comment]
@erick-u @JuanRMarquez-Ortiz Following today's Sprint Planning conversation, I think this PR is ready to merge. Would one of you mind handling the merge? It looks like there are a few conflicts.

**Comment by JuanRMarquez-Ortiz** [comment]
I'll look it over.

**Pull request merged**
