### PR TITLE
MCS-1495 Fixed a bug with resetting the filename counter for the topdown camera.

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
As reported on Slack, enabling the new Unity-based topdown camera when running multiple scenes with the same controller would cause errors like this:

```
Error in event with type=EventType.ON_START_SCENE to subscriber=<class 'machine_common_sense.controller_media.UnityTopdownCameraCombinerEventHandler'>
Traceback (most recent call last):
  File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/controller.py", line 550, in _publish_event
    subscriber.on_event(event_type, payload)
  File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/controller_events.py", line 115, in on_event
    self._switcher.get(
  File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/controller_media.py", line 222, in on_start_scene
    self.write_image(payload)
  File "/home/tschellenberg/Development/darpa/temp-mcs/machine_common_sense/controller_media.py", line 229, in write_image
    image = PIL.Image.open(image_file.as_posix())
  File "/home/tschellenberg/Development/darpa/temp-mcs/venv/lib/python3.8/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'eval_6_arithmetic_ex_2/eval_6_arithmetic_ex_2_topdown_0.png'
```

Brian identified (and I then confirmed) the issue was due to a variable in the topdown camera class not being correctly reset when the scene changed.

You can test this by running one of the developer scripts like `machine_common_sense/scripts/run_passive_scenes.py` on multiple scene files.

### CODE REVIEW

**Review by jaudick — APPROVED** [review]

**Review by rartiss55 — APPROVED** [review]
Looks like the images are numbered correctly. 

I probably missed it in the documentation/whatever PR it was, but is there a way to update the path for the output folder of the new top down images, in case your Unity build is in a different directory than the Python API code?

**Comment by rartiss55** [comment]
> @rartiss55
> 
> > is there a way to update the path for the output folder of the new top down images
> 
> Aren't they just saved in the same folder as all the other debug files (current_directory/scene_name)?

@ThomasSchellenbergNextCentury For me, the current_directory/ is wherever my Unity build lives when it comes to the new top down images (as opposed to where I'm running the Python API code). So if that isn't in the same directory, I have two different output folders with screenshots (python_directory/scene_name and unity_build_dir/scene_name) and the Python API side can't find the top down ones.

**Comment by ThomasSchellenbergNextCentury** [comment]
In `parameter.py`, in `wrap_step`, we're setting the `topDownImagePath` to the debug output folder, and in `MCSController.cs`, we're using that path while calling `TakeScreenshot`. I was pretty sure Alex had fixed this (as the code implies), and I can't find a Screenshots folder in the folder where my Unity build is located. Is it possible that some of your code is stale?

**Comment by brianpippin** [comment]
I see the same issue as Rachel using the latest MCS development branch where the topdown video is written to a different folder than the rest of the videos on my mac.

**Comment by ThomasSchellenbergNextCentury** [comment]
@rartiss55 @brianpippin If you run with `save_debug_images: true` and/or `save_debug_json: true`, where does they get saved?

**Comment by brianpippin** [comment]
> @rartiss55 @brianpippin If you run with `save_debug_images: true` and/or `save_debug_json: true`, where do they get saved?

It doesn't change the outcome for me.  I still get a scene_file_name folder where unity is, and a scene_file_name folder where the MCS api is.

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin @rartiss55 The output folder (for both the topdown and the debug files) is set to `f'./{scene_config.name}/'` in the Python API: https://github.com/NextCenturyCorporation/MCS/blob/development/machine_common_sense/controller.py#L215

I wonder if `./` is sometimes interpreted differently on Mac? Maybe you could try changing that line to the following:

```python
self.__output_folder = f'{os.getcwd()}/{scene_config.name}/'
```

**Comment by brianpippin** [comment]
> @brianpippin @rartiss55 The output folder (for both the topdown and the debug files) is set to `f'./{scene_config.name}/'` in the Python API: https://github.com/NextCenturyCorporation/MCS/blob/development/machine_common_sense/controller.py#L215
> 
> I wonder if `./` is sometimes interpreted differently on Mac? Maybe you could try changing that line to the following:
> 
> ```python
> self.__output_folder = f'{os.getcwd()}/{scene_config.name}/'
> ```

This change did the trick for me so long as it works on linux as well.  I think it was passing the relative path, and the relative path for unity was different from the relative path for the api, at least on the mac.

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin @rartiss55 Yep it worked for me too! PR: https://github.com/NextCenturyCorporation/MCS/pull/614

**Review by brianpippin — APPROVED** [review]

**Pull request merged**
