### PR TITLE
Mcs 95 config room size

### PR DESCRIPTION
**Pull request by kdrumm**
Adds ability to set room size in scene file.  Integration tests are in coming MCS pull request.

Many existing integration tests are failing, but were also failing prior to this work.

### CODE REVIEW

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Looks great! I also copied your two example scene files here for easier testing (hope you don't mind).

**Comment by rartiss55** [comment]
Code looks good. I did notice an issue moving around where it seemed like I couldn't move past a 
certain point with larger rooms (20x3x20 or the large_room example). I think what's happening is there's a SceneBounds that gets calculated before the new size of the room is read in. Calling agentManager.ResetSceneBounds() or some version of that code (there's a few similar examples in other files) after setting the room size should fix it.

**Comment by kdrumm** [comment]
Good find Rachel.  Updated with latest from development and fixed the bounds bug.  Do we need a re-approval?

**Review by rartiss55 — APPROVED** [review]
Approved -- the only other thing is documenting the issue with the visibility distance possibly being less than the max size of the room I mentioned at standup, but I think that goes in the associated Python code PR.

**Comment by ThomasSchellenbergNextCentury** [comment]
> Approved -- the only other thing is documenting the issue with the visibility distance possibly being less than the max size of the room I mentioned at standup, but I think that goes in the associated Python code PR.

@rartiss55 @kdrumm Would it be better to document the visibility distance limitation in the SCHEMA doc in the MCS repo?

**Pull request merged**
