### PR TITLE
MCS-1838 Added missing materials to MCSConfig.

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Realized during some recent testing that we were missing some materials for specific objects in here, because those objects didn't return anything in their `texture_color_list` metadata: https://nextcenturycorporation.github.io/MCS/api.html#machine_common_sense.ObjectMetadata

Also fixed a typo and moved the original tool material into the TOOL_MATERIALS

### CODE REVIEW

**Review by phile-caci — COMMENTED** [review]
Is there a good way for me to test for missing materials?

I rebuilt addressables:
Didn't see any warnings in the console.

Ran MCS integration using local AI2THor build, didn't see any errors in the addressables HTTP request, but saw these integration errors.

```
FAILED INTEGRATION TESTS:
    110.tool_cannot_walk_into (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
    111.tool_push (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
    112.tool_move (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
    113.tool_torque (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
    114.tool_rotate (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
    115.tool_push_into_soccer_ball (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
    116.tool_move_into_soccer_ball (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
    141.rotate_and_move_object_collide_with_performer (oracle): Step 0 failed:
        objects tool texture_color_list: ['grey'] != ['grey', 'black']
```

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci You can look at the "texture_color_list" property in the output ObjectMetadata when running via Python, or print out "colorsFromMaterials" where it gets assigned in MCSController.ObjectMetadataFromSimObjPhysics when running in the Unity Editor.

Those failing tests were recently fixed on development, so I'm assuming there's an issue with branches being out of sync that will fix itself when merged.

**Comment by phile-caci** [comment]
> @phile-caci You can look at the "texture_color_list" property in the output ObjectMetadata when running via Python, or print out "colorsFromMaterials" where it gets assigned in MCSController.ObjectMetadataFromSimObjPhysics when running in the Unity Editor.
> 
> Those failing tests were recently fixed on development, so I'm assuming there's an issue with branches being out of sync that will fix itself when merged.

Thanks Thomas. Looks like merging development did the trick.

**Review by phile-caci — APPROVED** [review]
LGTM!

**Pull request merged**
