### PR TITLE
MCS-1746 agents point at 45 degree angle

### PR DESCRIPTION
**Pull request by jaudick**
[Private](https://github.com/NextCenturyCorporation/mcs-private/pull/408)

### CODE REVIEW

**Review by ThomasSchellenbergNextCentury — CHANGES_REQUESTED** [review]
Not working for me (even running in the Unity Editor). I'm getting the following error message:

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
MCSSimulationAgent.IncrementAnimationFrame () (at Assets/Scripts/MCSSimulationAgent.cs:352)
MCSController.SimulatePhysicsOnce () (at Assets/Scripts/MCSController.cs:743)
MCSController.SimulatePhysics () (at Assets/Scripts/MCSController.cs:707)
MCSMain.Update () (at Assets/Scripts/MCSMain.cs:271)
```

Does the animation controller also need to be updated? I didn't see any changes to that file in your mcs-private branch.

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury That would do it, just pushed the fixed animator to private

**Review by phile-caci — APPROVED** [review]
Looks good to me.

1. Copied new Assets from mcs-private to ai2thor
2. Rebuilt addressables
3. Ran agents_pointing.json in MCS and Unity

image

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Looks good for now. KDL may request adjustments as we begin implementing Knowledgeable Agents, but we'll just handle it then if necessary.

**Pull request merged**
