### PR TITLE
MCS-984 (New) - Make an Addressable Version of the Main MCS Unity Scene

### PR DESCRIPTION
**Pull request by alexcraneunity**
Jira: https://nextcentury.atlassian.net/browse/MCS-984

Recreated this using the MCS-984-new branch instead of MCS-984, so we can delete that branch and the TextMesh Pro branch it's based off it. Because of this, I will be closing out [the old PR](https://github.com/NextCenturyCorporation/ai2thor/pull/177). 

Below is the very basic loading scene using the DARPA logo. The text will change based on whether a scene load was successful or failed.
image

### CODE REVIEW

**Comment by kdrumm** [comment]
I tried testing this and saw no change.  I'm currently under the assumption that it was user error and am attempting again.  Have anyone else tried yet?

**Comment by ThomasSchellenbergNextCentury** [comment]
I'm also seeing no change from the previous PR. I'm getting the same exception, both when running the integration tests (which hang indefinitely on test 083), and when running an individual scene containing a hole:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at MCSMain.CreateHolesAndApplyFloorTextures () [0x00324] in /home/tschellenberg/Development/darpa/ai2thor/unity/Assets/Scripts/MCSMain.cs:598
  at MCSMain.AdjustRoomStructuralObjects () [0x00d7e] in /home/tschellenberg/Development/darpa/ai2thor/unity/Assets/Scripts/MCSMain.cs:533
  at MCSMain.ChangeCurrentScene (MCSConfigScene scene) [0x00160] in /home/tschellenberg/Development/darpa/ai2thor/unity/Assets/Scripts/MCSMain.cs:283
  at MCSController.Initialize (ServerAction action) [0x00054] in /home/tschellenberg/Development/darpa/ai2thor/unity/Assets/Scripts/MCSController.cs:279
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <eae584ce26bc40229c1b1aa476bfa589>:0
   --- End of inner exception stack trace ---
```

I've rebuilt addressables locally (using the Localhost profile) off the new branch, along with a new Unity build, and can see that the addressables are correctly being accessed off my python HTTP server. I've also made sure that the BuildPath, LoadPath, and MonoScript Bundle Naming Prefix are correct in my local Addressable Asset Settings. Is there anything else I've forgotten to do?

I remember that, before the break, we discussed replacing the `Instantiate` call (MCSMain line 590) as a fall back, so we can always do that, if other investigations fail to bear any fruit.

**Comment by alexcraneunity** [comment]
@kdrumm @ThomasSchellenbergNextCentury I figured out what caused this. My last commit, which removed "holes" from the default scene parameter in the MCS-Starter-Scene, is what broke it. I reverted to one commit before that and can get it to run through all the tests again. I'm not sure why this change would cause it to hang on test 83 again, but I'm also not sure why the default local group was changed in that commit too, so I'm investigating it. I'll push a revert so you can test properly first.

**Comment by kdrumm** [comment]
This now works for me, but if I remove holes from the default scene it still errors.  I don't think we want to NEED holes to be the default scene and this probably means there is still an underlying issue.  Thoughts from others?

**Comment by ThomasSchellenbergNextCentury** [comment]
@alexcraneunity To follow up after this morning's standup -- findings from some local testing:
- I tried changing the Default Scene File to another scene (without holes), to see if it worked, but it didn't.
- I'm assuming this is still an initialization/load order issue. Maybe we should try to instantiate some mock floor sections on Start()?
- Side note, but I don't think that we're correctly cleaning up the old floor sections we instantiate when changing the current scene.
- We should make sure to test scenes with holes in various positions, and rooms of various sizes, loaded sequentially with the same MCS controller.

**Comment by alexcraneunity** [comment]
@ThomasSchellenbergNextCentury  @kdrumm I finally got around to testing my theory that having "holes" in both MCS.unity and MCS-Starter-Scene's default scene parameter was the issue, and that removing it from just one caused a problem. I removed it from both and ran tests in a new build, and unfortunately it still gets hung up at test 83. No errors are printed, but I grabbed these from the logs:
`The referenced script (Unknown) on this Behaviour is missing! 

(Filename:  Line: 199)



The referenced script (Unknown) on this Behaviour is missing! 

(Filename:  Line: 199)



The referenced script on this Behaviour (Game Object 'Floor') is missing! 

(Filename:  Line: 334)



The referenced script on this Behaviour (Game Object 'Floor') is missing! 

(Filename:  Line: 334)



The referenced script on this Behaviour (Game Object 'Floor') is missing! 

(Filename:  Line: 334)



The referenced script on this Behaviour (Game Object 'Floor') is missing! 

(Filename:  Line: 334)`

I would definitely still assume this is an initialization/load order issue, though I'm not sure why loading the holes scene first through the default scene parameter causes it to load everything correctly, when compared to loading it later.

**Comment by alexcraneunity** [comment]
I was able to remove the holes scene parameter and resolve the bug by making the floor a prefab again. Previously, when the floors were destroyed and recreated for the holes scene, since the floor wasn't addressable it wasn't being instantiated properly. Making the floor an addressable should guarantee that the application knows where to look to find all the needed info from the floor object.

**Comment by kdrumm** [comment]
I ran this and it seems to work.  I'm getting a bunch of integration test errors that I'm curious about.  I don't think what you did would cause them.  I want to look into it further but won't be able to until after next week.

**Comment by alexcraneunity** [comment]
@kdrumm I just finished re-running all tests, and I didn't get any integration test errors. Would you be able to share what errors you got?

**Review by ThomasSchellenbergNextCentury — CHANGES_REQUESTED** [review]
1. The `soccer_ball` wasn't showing up in my scenes correctly, and I noticed some modified files in this PR. Since these changes shouldn't affect the soccer ball, I went ahead and reverted those files to what's currently on `development`, which fixed the issue.
2. In MCS-Starter-Scene, "holes" is still set as the "defaultSceneFile" in the committed version of the file. Removing "holes" causes the same issue as before (with the "referenced script on this Behavior is missing" and NullReferenceException errors). I'm wondering if @kdrumm tested using the code that's committed, which still includes the "holes" setting?

**Comment by alexcraneunity** [comment]
@ThomasSchellenbergNextCentury This morning I confirmed that the holes parameter hadn't properly been removed before my testing, so your observations are correct. I re-ran the tests after removing it again and I received the same errors. Today I will look over your code review #190 and we can hopefully get that merged into this branch to proceed.

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Review by kdrumm — APPROVED** [review]

**Pull request merged**
